#!/usr/bin/env python
#
# Basic webscraper. Given a URL print all anchor tag
# URIs
#
# Usage: scrape-img http://www.cc.gatech.edu/~ynadji3
#
# returns:
#
# http://www.cc.gatech.edu/~ynadji3/images/profile.jpg
# ...
# http://www.w3.org/Icons/valid-xhtml10-blue#
#

from scrape import *

import sys,os

if len(sys.argv) != 2:
    print "usage: scrape URL"
    sys.exit(2)

main_region = s.go(sys.argv[1])
all = main_region.alltags('img')
for r in all:
    print s.resolve(r.__getitem__('src'))
